apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainpage-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainpage-dev
  template:
    metadata:
      labels:
        app: mainpage-dev
    spec:
      containers:
      - name: mainpage-dev
        image: benjaminucn/devops-taller-mainpage:dev
        envFrom: 
        - secretRef:
            name: mainpage-dev-secret
        ports:
        - containerPort: 3004
        resources:
          requests:
            memory: "64Mi"
            cpu: "80m"
          limits:
            memory: "128Mi"
            cpu: "100m"  